export const main = "/"
export const adminPanel = "/panel"
export const clientPanel = "/"
export const users = "/panel/users"
export const products = "/panel/products"
export const orders = "/panel/orders"