export const main = "/"
export const adminPanel = "/panel"
export const clientPanel = "/client"
export const adminPanelUsers = "/panel/users"
export const adminPanelProducts = "/panel/products"
export const adminPanelOrders = "/panel/orders"